### ISSUE TITLE
Example of ignored files

### ISSUE THREAD

**Issue by brunowego** [demones/react-webpack-node#1]
Can you provide a example of `client/config/index.js`, `client/containers/Root.js` and `client/store/index.js`?

Thanks!

**Comment by hopefuture** [comment]
You can exec command "gulp server" to generate automatically these files. This version is imperfect.
I will provide a powerful  React Boilerplate in next version. Looking forward to.
Thanks!

**Comment by brunowego** [comment]
That's great, thanks!

**Comment by hopefuture** [comment]
The newest version has published. You can clone it and use it.
